require: rubocop-rspec

Style/Documentation:
  Enabled: false

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
